"""owner table added

Revision ID: 787037291c37
Revises: 2b7e4e82e8f7
Create Date: 2020-03-13 16:41:42.972094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787037291c37'
down_revision = '2b7e4e82e8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
