"""users and admin added

Revision ID: 99aa697db01a
Revises: 
Create Date: 2020-03-19 19:26:05.593619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99aa697db01a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homeusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('devicename', sa.String(length=64), nullable=True),
    sa.Column('macaddress', sa.String(length=17), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homeusers_macaddress'), 'homeusers', ['macaddress'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homeusers_macaddress'), table_name='homeusers')
    op.drop_table('homeusers')
    op.drop_table('admin')
    # ### end Alembic commands ###
